/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class FastTest {
    @Test public void appHasAGreeting() {
        assertEquals(0, 0);
    }
}
